server:
  port: 7001

spring:
  application:
    name: netty-test-first
  profiles:
    active: dev # 当前环境: 开发
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127:0:0:1:8848 # 注册入的nacos服务地址
      config: # ${prefix}-${spring.profile.active}.${file-extension}
        server-addr: 127:0:0:1:8848 # 从nacos配置中心拉取
        group: default # 配置所在的组
        namespace: public # 配置所在的命名空间
        file-extension: yaml # 配置的后缀
        prefix: ${spring.application.name}
    sentinel:
      transport:
        port: 8858
        dashboard: http://127.0.0.1:8858

#    gateway:
#      discovery:
#        locator:
#          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
#      routes:
#        - id: netty-test-first # 唯一，建议与服务器名保持一致
##          uri: http://localhost:8001
#          uri: lb://NETTY-TEST-FIRST # 匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/get/** # 断言，路径相匹配的进行路由